apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcon-inference
  template:
    metadata:
      labels:
        app: falcon-inference
    spec:
      containers:
      - name: falcon-inference
        image: aksclust1acr.azurecr.io/falcon-inference:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1  # Request one GPU
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"